# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    #1-1. repository checkout
    - uses: actions/checkout@v4

    # 1-2. jdk 환경 설치
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'


    # 1-3. 'application.yml' 파일 세팅
    - name: application.yml 파일 설정
      run: |
        mkdir -p src/main/resources
        echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
        
        # mkdir -p src/test/resources
        # echo "${{ secrets.TEST_APPLICATION_YML }}" > ./src/test/resources/application.yml

    # 1-4. gradle 환경 설치
    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # 1-5. 빌드
    - name: Build with Gradle Wrapper
      run: ./gradlew clean build -x test

    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    #   with:
    #     gradle-version: '8.9'
    #
    # - name: Build with Gradle 8.9
    #   run: gradle build

    # 1-6. 빌드된 파일 이름 변경
    - name: 빌드된 파일 이름 변경하기
      run: mv ./build/libs/*SNAPSHOT.jar ./HealthCare.jar
      
    # 1-7. 빌드 및 이름 변경된 HealthCare.jar 파일 EC2 전송 
    - name: SCP로 EC2에 빌드된 파일 전송하기
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: HealthCare.jar
        target: /home/ubuntu/healthcare
        
  #2. 배포
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    # 2-1. EC2 접속 및 jar 파일 실행
    - name: SSH로 EC2에 접속하기
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          # 1. 기존 8080 포트 사용하는 프로세스 종료
          sudo fuser -k -n tcp 8080 || true

          # 2. 실행 디렉토리 이동
          cd /home/ubuntu/healthcare

          # 3. 새 JAR 실행
          sudo nohup java -jar HealthCare.jar > ./output.log 2>&1 &
